# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  #schedule:
  #- cron: "*/5 * * * *"
  
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-node@v3
       with:
        node-version: 14
     - run: node index.js
    
     - name: update file and push to remote
       run: |
         git config --global user.name "prankGG"
         git config --global user.email "prankgg@real.email"

         git add -A
         git commit -m "sussy baka"
         git push
